### ISSUE TITLE
Unable to catchup

### ISSUE THREAD

**Issue by soledadescobar** [stargately/blockroma#49]
*Describe your issue here.*
En V1:
   If I start the app with catchup disalbled it works fine and I can see the new blocks. 
   If I start the app enabling  catchup I get the following error:

[server] error: failed to mountBlockCatchupFetcher: TypeError: blockNumberRanges is not iterable
TypeError: blockNumberRanges is not iterable
    at mountBlockCatchupFetcher (/home/justech/blockroma-main/v1/src/indexer/block-catchup-fetcher.ts:22:27)
    at startServer (/home/justech/blockroma-main/v1/src/server/start-server.ts:56:27)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

### Environment
Ubuntu 22.04
Node 16.20.

* Blockchain: *which blockchain is it?*
Hyperledger Besu
* Blockroma Version: *when did you find the problem?*
latest
* User Agent: *describe your operating system and browser*
Ubuntu 22.04
Chrome
### Steps to reproduce
Change in config/default.js
indexer: {
    catchup: {
      enabled: true,
    },
Restart the app. 

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally. A screenshot would be very helpful. If it's UI problem, what is the URL?*
I downloaded the zip file from main branch. 
### Expected Behaviour

*Tell us what should happen.*
It should include all the blocks in the blockchain since the beginning. 
### Actual Behaviour
*Tell us what happens instead.*
I can only load blocks while the pp is running. 

Thank you!

**Comment by soledadescobar** [comment]
Just in case it helps someone the problem was solved by adding in file config/default.js:
indexer: {
    catchup: {
      enabled: true,
      blocksBatchSize: 200,
      blockNumberRanges: [
        [0, "latest"], // range to scan
      ],
    },

**Comment by soledadescobar** [comment]
It works perfectly.
